language: go
# sudo: false
go:
  - 1.6
  - 1.7
  - tip

env:
  global:
    - GOARCH=amd64
    - GO15VENDOREXPERIMENT=1

branches:
  only:
    - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libmagic-dev

install: make deps
script:
  - go build -o new_malice
